import type { Metadata } from "next";
import React, { ReactNode } from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"], weight: "200" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <>
          <ol>
            <li>
              <Link href={"/"}>Go Home Page</Link>
            </li>
            <li>
              <Link href={"/about"}>Go to About</Link>
            </li>
            <li>
              <Link href={"/contact"}>Go to Contact</Link>
            </li>
          </ol>
          {children}
        </>
      </body>
    </html>
  );
}
